<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MemoryInspector.Plugin</RootNamespace>
    <AssemblyName>MemoryInspector.Plugin</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MemoryInspector.Common\MemoryInspector.Common.csproj" />
  </ItemGroup>
</Project>
